name: Run CsvExpiryProcessor

on:
  schedule:
    - cron: '*/5 * * * *'         # Runs every 5 minutes
  workflow_dispatch:              # Manual run from GitHub UI
  push:
    branches:
      - main                      # Runs on push to main branch
  pull_request:
    branches:
      - main                      # Runs on PR targeting main branch

jobs:
  run-processor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Show repo files (debugging)
      run: ls -R

    - name: Run CsvExpiryProcessor
      run: python CertExpiryProcessor/CertExpiryProcessor.py
